[tool.poetry]
name = "filedispatch"
version = "0.1.0"
description = ""
authors = ["Aristide <aristide.bamazi@imsp-uac.org>"]

[tool.poetry.dependencies]
python = "^3.10"
pydantic-yaml = "^0.8.0"
pytest-mock = "^3.8.2"
mode = { git = "https://github.com/aristidebm/mode.git" }
# The depencicies is pinned to v0.15 because of this https://github.com/samuelcolvin/watchfiles/issues/177
watchfiles = "0.15"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
pytest = "^7.1.2"
flake8 = "^5.0.4"
pytest-asyncio = "^0.19.0"
pre-commit = "^2.20.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
